# Generated by Django 2.1.4 on 2019-08-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='sales_date',
            new_name='sale_date',
        ),
    ]
