# Generated by Django 2.1.4 on 2019-08-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20190807_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
