# Generated by Django 2.1.4 on 2019-08-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20190807_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.IntegerField(db_column='baths'),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.IntegerField(db_column='beds'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(db_column='city', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(db_column='latitude', decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(db_column='longitude', decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(db_column='price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_date',
            field=models.DateField(db_column='sale_date'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sq_ft',
            field=models.IntegerField(db_column='sq__ft'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(db_column='state', max_length=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(db_column='street', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(db_column='type', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip',
            field=models.IntegerField(db_column='zip'),
        ),
        migrations.AlterModelTable(
            name='property',
            table='sacramento',
        ),
    ]
