# Generated by Django 2.1.4 on 2019-08-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20190807_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='sq_ft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='property',
            table=None,
        ),
    ]
