# Generated by Django 2.1.4 on 2019-08-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20190808_0306'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='properties_property',
        ),
    ]
