# Generated by Django 2.1.4 on 2019-08-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20190808_0311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
