# Generated by Django 2.1.4 on 2019-08-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0009_delete_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('sq_ft', models.IntegerField()),
                ('type', models.CharField(max_length=25)),
                ('sale_date', models.DateField()),
                ('price', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=6)),
            ],
        ),
    ]
