# Generated by Django 2.1.4 on 2019-08-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='street',
            field=models.TextField(max_length=50),
        ),
    ]
