# Generated by Django 2.1.4 on 2019-08-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20190808_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
