# Generated by Django 2.1.4 on 2019-08-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20190808_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
