# Generated by Django 2.1.4 on 2019-08-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20190808_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='sale_date',
            field=models.DateTimeField(),
        ),
    ]
